<?php

namespace {{namespace}};

use PHPNomad\Events\Interfaces\CanHandle;
use PHPNomad\Events\Interfaces\Event as PHPNomadEvent;

/**
 * Enqueues a JavaScript bundle on the front-end and/or in wp-admin.
 *
 * The companion {{handle}}.asset.php file (generated by @wordpress/scripts) is
 * read for dependencies and version. If you're not using @wordpress/scripts,
 * edit getAssetMeta() to return your own dependency list and version.
 *
 * @see https://developer.wordpress.org/reference/functions/wp_enqueue_script/
 */
class {{name}} implements CanHandle
{
    public const HANDLE = '{{handle}}';

    public function __construct(private readonly string $pluginUrl, private readonly string $pluginPath)
    {
    }

    public function handle(PHPNomadEvent $event): void
    {
        add_action('wp_enqueue_scripts', [$this, 'enqueue']);
        add_action('admin_enqueue_scripts', [$this, 'enqueue']);
    }

    public function enqueue(): void
    {
        if (!$this->shouldEnqueue()) {
            return;
        }

        $asset = $this->getAssetMeta();

        wp_enqueue_script(
            self::HANDLE,
            $this->pluginUrl . '{{srcPath}}',
            $asset['dependencies'],
            $asset['version'],
            true
        );
    }

    private function shouldEnqueue(): bool
    {
        // TODO: gate the script — e.g. only on certain admin screens or post types.
        return true;
    }

    /**
     * @return array{dependencies: string[], version: string}
     */
    private function getAssetMeta(): array
    {
        $assetFile = $this->pluginPath . '{{assetMetaPath}}';

        if (file_exists($assetFile)) {
            $meta = include $assetFile;
            return [
                'dependencies' => $meta['dependencies'] ?? [],
                'version' => $meta['version'] ?? '1.0.0',
            ];
        }

        return ['dependencies' => [], 'version' => '1.0.0'];
    }
}
